/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.dtd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DtdLanguageUiModule extends nl.dslmeinte.xtext.dtd.ui.AbstractDtdLanguageUiModule {
	public DtdLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
