/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.examples.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DataModelDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
