
/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.examples.ui.internal;

import org.apache.log4j.Logger;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.util.Modules;

import java.util.Map;
import java.util.HashMap;

/**
 * Generated
 */
public class XsdLanguageActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static XsdLanguageActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		try {
			
			injectors.put("nl.dslmeinte.xtext.examples.XsdLanguage", Guice.createInjector(
				Modules.override(Modules.override(getRuntimeModule("nl.dslmeinte.xtext.examples.XsdLanguage")).with(getUiModule("nl.dslmeinte.xtext.examples.XsdLanguage"))).with(getSharedStateModule())
			));
			
		} catch (Exception e) {
			Logger.getLogger(getClass()).error(e.getMessage(), e);
			throw e;
		}
	}
	
	public static XsdLanguageActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		
		if ("nl.dslmeinte.xtext.examples.XsdLanguage".equals(grammar)) {
		  return new nl.dslmeinte.xtext.examples.XsdLanguageRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	protected Module getUiModule(String grammar) {
		
		if ("nl.dslmeinte.xtext.examples.XsdLanguage".equals(grammar)) {
		  return new nl.dslmeinte.xtext.examples.ui.XsdLanguageUiModule(this);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
