/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.examples.ui.contentassist;

import nl.dslmeinte.xtext.examples.ui.contentassist.AbstractAmbiguityDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AmbiguityDslProposalProvider extends AbstractAmbiguityDslProposalProvider {

}
