/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.sgml.base;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BaseRuntimeModule extends nl.dslmeinte.xtext.sgml.base.AbstractBaseRuntimeModule {

}
