<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xsdLanguage"
    nsURI="http://www.dslmeinte.nl/xtext/examples/XsdLanguage" nsPrefix="xsdLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//TopLevelDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelType" eSuperTypes="#//TopLevelDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelElement" eSuperTypes="#//TopLevelDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//NamedTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedTypeDef" eType="#//EmbeddedType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelSimpleType" eSuperTypes="#//TopLevelType #//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Restriction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//NonComplexTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//Facet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Facet"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationFacet" eSuperTypes="#//Facet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxLengthFacet" eSuperTypes="#//Facet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternFacet" eSuperTypes="#//Facet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeFacet" eSuperTypes="#//Facet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LengthFacet" eSuperTypes="#//Facet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Documentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelComplexType" eSuperTypes="#//TopLevelType #//ComplexType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//NamedTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedTypeDef" eType="#//EmbeddedType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//NonComplexTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unbounded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonComplexTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltinTypeReference" eSuperTypes="#//NamedTypeReference #//NonComplexTypeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="builtin" eType="#//BuiltinType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelTypeReference" eSuperTypes="#//NamedTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//TopLevelType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelComplexTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//TopLevelComplexType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelSimpleTypeReference" eSuperTypes="#//NonComplexTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//TopLevelSimpleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectTopLevelTypeReference" eSuperTypes="#//TopLevelTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectTopLevelSimpleTypeReference" eSuperTypes="#//TopLevelSimpleTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectTopLevelComplexTypeReference"
      eSuperTypes="#//TopLevelComplexTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportedTopLevelTypeReference" eSuperTypes="#//TopLevelTypeReference #//ImportedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportedTopLevelSimpleTypeReference"
      eSuperTypes="#//TopLevelSimpleTypeReference #//ImportedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportedTopLevelComplexTypeReference"
      eSuperTypes="#//TopLevelComplexTypeReference #//ImportedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportedReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" eType="#//Import"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedComplexType" eSuperTypes="#//EmbeddedType #//ComplexType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedSimpleType" eSuperTypes="#//EmbeddedType #//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//TopLevelComplexTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="restriction" eType="#//Restriction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentation" eType="#//Documentation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltinType">
    <eLiterals name="duration" literal="duration"/>
    <eLiterals name="dateTime" value="1" literal="dateTime"/>
    <eLiterals name="time" value="2" literal="time"/>
    <eLiterals name="date" value="3" literal="date"/>
    <eLiterals name="string" value="4" literal="string"/>
    <eLiterals name="decimal" value="5" literal="decimal"/>
    <eLiterals name="integer" value="6" literal="integer"/>
    <eLiterals name="positiveInteger" value="7" literal="positiveInteger"/>
    <eLiterals name="nonNegativeInteger" value="8" literal="nonNegativeInteger"/>
    <eLiterals name="token" value="9" literal="token"/>
    <eLiterals name="base64Binary" value="10" literal="base64Binary"/>
  </eClassifiers>
</ecore:EPackage>
